services:
  - type: web
    name: selenios-3
    env: python
    region: oregon
    plan: free
    runtime: python-3.11  
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app